/**
 * Données de Secours (Mock & Mode Hors Ligne) pour le Lancement Pilote MarketRadar
 * Utilisé automatiquement lorsque Supabase n'est pas joignable (ERR_NAME_NOT_RESOLVED) ou hors-ligne.
 */

export const MOCK_CITIES = [
  { id: 'city-ouaga', name: 'Ouagadougou', country: 'Burkina Faso', region: 'Centre' },
  { id: 'city-bobo', name: 'Bobo-Dioulasso', country: 'Burkina Faso', region: 'Hauts-Bassins' },
  { id: 'city-koudougou', name: 'Koudougou', country: 'Burkina Faso', region: 'Centre-Ouest' },
  { id: 'city-ouahigouya', name: 'Ouahigouya', country: 'Burkina Faso', region: 'Nord' },
  { id: 'city-gaoua', name: 'Gaoua', country: 'Burkina Faso', region: 'Sud-Ouest' },
];

export const MOCK_MARKETS = [
  {
    id: 'mkt-roodwoko',
    name: 'Grand Marché Rood Woko',
    city_id: 'city-ouaga',
    city_name: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3714,
    longitude: -1.5197,
  },
  {
    id: 'mkt-sankariare',
    name: 'Marché de Sankariaré',
    city_id: 'city-ouaga',
    city_name: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3789,
    longitude: -1.5235,
  },
  {
    id: 'mkt-bobo-grand',
    name: 'Grand Marché de Bobo',
    city_id: 'city-bobo',
    city_name: 'Bobo-Dioulasso',
    region: 'Hauts-Bassins',
    latitude: 11.1771,
    longitude: -4.2979,
  },
  {
    id: 'mkt-nieneta',
    name: 'Marché de Nieneta',
    city_id: 'city-bobo',
    city_name: 'Bobo-Dioulasso',
    region: 'Hauts-Bassins',
    latitude: 11.185,
    longitude: -4.285,
  },
  {
    id: 'mkt-koudougou-central',
    name: 'Grand Marché de Koudougou',
    city_id: 'city-koudougou',
    city_name: 'Koudougou',
    region: 'Centre-Ouest',
    latitude: 12.2514,
    longitude: -2.3622,
  },
  {
    id: 'mkt-ouahigouya-central',
    name: 'Grand Marché de Ouahigouya',
    city_id: 'city-ouahigouya',
    city_name: 'Ouahigouya',
    region: 'Nord',
    latitude: 13.5828,
    longitude: -2.4216,
  },
  {
    id: 'mkt-gaoua-central',
    name: 'Grand Marché de Gaoua',
    city_id: 'city-gaoua',
    city_name: 'Gaoua',
    region: 'Sud-Ouest',
    latitude: 10.3276,
    longitude: -3.1818,
  },
];

export const MOCK_PRODUCTS = [
  { id: 'prod-mais', name: 'Sac de Maïs (100kg)', category: 'Céréales', unit: 'sac 100kg', reference_price: 21000 },
  { id: 'prod-mil', name: 'Mil Local (kg)', category: 'Céréales', unit: 'kg', reference_price: 280 },
  { id: 'prod-riz', name: 'Riz Local Kam (50kg)', category: 'Céréales', unit: 'sac 50kg', reference_price: 18500 },
  { id: 'prod-huile', name: 'Huile Savor (5L)', category: 'Epicerie', unit: 'bidon 5L', reference_price: 5850 },
  { id: 'prod-boeuf', name: 'Viande de Boeuf (kg)', category: 'Viandes', unit: 'kg', reference_price: 3150 },
  { id: 'prod-sucre', name: 'Sucre de Canne (kg)', category: 'Epicerie', unit: 'kg', reference_price: 800 },
  { id: 'prod-tomate', name: 'Tomate Locale (Caisse)', category: 'Legumes', unit: 'caisse', reference_price: 12000 },
  { id: 'prod-mangue', name: 'Mangue Amélie (Carton 40kg)', category: 'Fruits', unit: 'carton', reference_price: 8500 },
];

export const MOCK_PRICES = [
  {
    id: 'prc-1',
    product_id: 'prod-mais',
    market_id: 'mkt-roodwoko',
    price_value: 21000,
    unit: 'sac 100kg',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'trusted',
    reliability_score: 0.95,
    products: { name: 'Sac de Maïs (100kg)', category: 'Céréales', unit: 'sac 100kg' },
    markets: { name: 'Grand Marché Rood Woko', city_id: 'city-ouaga' },
  },
  {
    id: 'prc-2',
    product_id: 'prod-mais',
    market_id: 'mkt-bobo-grand',
    price_value: 15750,
    unit: 'sac 100kg',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'trusted',
    reliability_score: 0.92,
    products: { name: 'Sac de Maïs (100kg)', category: 'Céréales', unit: 'sac 100kg' },
    markets: { name: 'Grand Marché de Bobo', city_id: 'city-bobo' },
  },
  {
    id: 'prc-3',
    product_id: 'prod-mil',
    market_id: 'mkt-roodwoko',
    price_value: 280,
    unit: 'kg',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'confirmed',
    reliability_score: 0.88,
    products: { name: 'Mil Local (kg)', category: 'Céréales', unit: 'kg' },
    markets: { name: 'Grand Marché Rood Woko', city_id: 'city-ouaga' },
  },
  {
    id: 'prc-4',
    product_id: 'prod-huile',
    market_id: 'mkt-sankariare',
    price_value: 5850,
    unit: 'bidon 5L',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'trusted',
    reliability_score: 0.96,
    products: { name: 'Huile Savor (5L)', category: 'Epicerie', unit: 'bidon 5L' },
    markets: { name: 'Marché de Sankariaré', city_id: 'city-ouaga' },
  },
  {
    id: 'prc-5',
    product_id: 'prod-boeuf',
    market_id: 'mkt-koudougou-central',
    price_value: 2678,
    unit: 'kg',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'confirmed',
    reliability_score: 0.85,
    products: { name: 'Viande de Boeuf (kg)', category: 'Viandes', unit: 'kg' },
    markets: { name: 'Grand Marché de Koudougou', city_id: 'city-koudougou' },
  },
  {
    id: 'prc-6',
    product_id: 'prod-mangue',
    market_id: 'mkt-gaoua-central',
    price_value: 7500,
    unit: 'carton',
    quantity: 1,
    created_at: new Date().toISOString(),
    reliability_status: 'trusted',
    reliability_score: 0.94,
    products: { name: 'Mangue Amélie (Carton 40kg)', category: 'Fruits', unit: 'carton' },
    markets: { name: 'Grand Marché de Gaoua', city_id: 'city-gaoua' },
  },
];

export const MOCK_DASHBOARD_SUMMARY = MOCK_PRICES.map((p) => ({
  product_id: p.product_id,
  market_id: p.market_id,
  product_name: p.products.name,
  product_category: p.products.category,
  product_unit: p.unit,
  market_name: p.markets.name,
  city_id: p.markets.city_id,
  latest_price: p.price_value,
  previous_price: Math.round(p.price_value * 1.05),
  change_percent: -4.8,
  trend: [Math.round(p.price_value * 1.05), p.price_value],
  shop_name: 'Boutique Pilote',
  shop_verified: true,
  seller_id: null,
  shop_trust_score: Math.round(p.reliability_score * 100),
}));

